name: Release Notification

on:
  release:
    types:
      - published

  workflow_dispatch:

jobs:
  notification:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || !github.event.release.prerelease }}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - name: Check npm cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ steps.npm-cache.outputs.dir }}
          key: npm-20.x-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-20.x-
            npm-

      - name: Setup deps & scripts
        run: |
          npm init -y
          npm install oceanic.js@~1.11.0 candyget@~0.5.4 dotenv@^16.4.5
          curl -Lo notification.js https://github.com/${{ github.repository }}/raw/${{ github.ref_name }}/util/notification.js

      - name: Run notification
        run: node notification
        env:
          TOKEN: ${{ secrets.Y_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          ROLE_ID: ${{ secrets.HOOK_ROLE_ID }}
          REPO_NAME: ${{ github.repository }}
